services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  categories-api:
    image: ryuzakizeitan/categorias:latest
    container_name: categories-service
    ports:
      - "8089:8089"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network
    restart: on-failure

  products-api:
    image: ryuzakizeitan/productos:latest
    container_name: products-service
    ports:
      - "8088:8088"
    depends_on:
      mysql-db:
        condition: service_healthy
      categories-api:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      CATEGORIES_SERVICE_URL: http://categories-api:8089
      CATEGORIES_API_URL: http://categories-api:8089/api/categorias
    networks:
      - app-network
    restart: on-failure

  frontend:
    image: ryuzakizeitan/frontend-products-cats:latest
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - categories-api
      - products-api
    networks:
      - app-network
    restart: on-failure

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge